nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Request-Headers', 'Access-Control-Request-Method', 'bearer', 'accept']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
            allow_headers: ['*']
            expose_headers: [ 'Link' ]
            max_age: 3600
